!
! FRRouting configuration file
!
password zebra
enable password zebra
!
log file /var/log/frr/frr.log
!
!  BGP CONFIGURATION
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
! 
! YOUR OWN CONFIGURATION: MODIFY BELOW 
!
router bgp 300
no bgp network import-check
neighbor 4.4.4.20 remote-as 200
neighbor 4.4.4.20 description Router 2 of AS200
network 5.5.5.0/24

neighbor 4.4.4.20 prefix-list routerIn in
neighbor 4.4.4.20 prefix-list routerOut out

ip prefix-list routerIn permit 1.1.1.0/24
ip prefix-list routerIn permit 2.2.2.0/24
ip prefix-list routerIn permit 3.3.3.0/24

ip prefix-list routerOut permit 5.5.5.0/24