!
! FRRouting configuration file
!
password zebra
enable password zebra
!
log file /var/log/frr/frr.log
!
!  BGP CONFIGURATION
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
! 
! YOUR OWN CONFIGURATION: MODIFY BELOW 
!
router bgp 200
no bgp network import-check
neighbor 2.2.2.10 remote-as 100
neighbor 2.2.2.10 description Router 1 of AS100

neighbor 4.4.4.30 remote-as 300
neighbor 4.4.4.30 description Router 3 of AS300

network 2.2.2.0/24
network 3.3.3.0/24
network 4.4.4.0/24

neighbor 2.2.2.10 prefix-list routerInR1 in
neighbor 2.2.2.10 prefix-list routerOutR1 out

ip prefix-list routerInR1 permit 1.1.1.0/24

ip prefix-list routerOutR1 permit 3.3.3.0/24
ip prefix-list routerOutR1 permit 4.4.4.0/24
ip prefix-list routerOutR1 permit 5.5.5.0/24

neighbor 4.4.4.30 prefix-list routerInR2 in
neighbor 4.4.4.30 prefix-list routerOutR2 out

ip prefix-list routerInR2 permit 5.5.5.0/24

ip prefix-list routerOutR2 permit 1.1.1.0/24
ip prefix-list routerOutR2 permit 2.2.2.0/24
ip prefix-list routerOutR2 permit 3.3.3.0/24