!
! FRRouting configuration file
!
password zebra
enable password zebra
!
log file /var/log/frr/frr.log
!
!  BGP CONFIGURATION
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
! 
! YOUR OWN CONFIGURATION: MODIFY BELOW 
!
router bgp 100
no bgp ebgp-requires-policy
no bgp network import-check
neighbor 2.2.2.20 remote-as 200
neighbor 2.2.2.20 description Router 2 of AS200
network 1.1.1.0/24

