!
! FRRouting configuration file
!
password zebra
enable password zebra
!
log file /var/log/frr/frr.log
!
!  BGP CONFIGURATION
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
debug rip event
!
network 10.1.1.0/24
router rip   

router bgp 65003
no bgp network import-check

network 10.1.1.0/24
network 172.16.1.0/24

neighbor 198.51.100.6 remote-as 65002
neighbor 198.51.100.6 description Router isp2 of 65002

neighbor 198.51.100.2 remote-as 65001
neighbor 198.51.100.2
 description Router isp1 of 65001

neighbor 198.51.100.6 prefix-list routerInisp2 in
neighbor 198.51.100.6 prefix-list routerOutisp2 out
neighbor 198.51.100.2 prefix-list routerInisp1 in
neighbor 198.51.100.2 prefix-list routerOutisp1 out

ip prefix-list routerInisp2 deny 10.1.1.0/24
ip prefix-list routerInisp2 deny 172.16.1.0/24
ip prefix-list routerInisp2 permit 0.0.0.0/0

ip prefix-list routerOutisp2 permit 10.1.1.0/24
ip prefix-list routerOutisp2 permit 172.16.1.0/24

ip prefix-list routerInisp1 deny 10.1.1.0/24
ip prefix-list routerInisp1 deny 172.16.1.0/24
ip prefix-list routerInisp1 permit 0.0.0.0/0

ip prefix-list routerOutisp1 permit 10.1.1.0/24
ip prefix-list routerOutisp1 permit 172.16.1.0/24
