!
! FRRouting configuration file
!
password zebra
enable password zebra
!
log file /var/log/frr/frr.log
!
!  BGP CONFIGURATION
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
! 
! YOUR OWN CONFIGURATION: MODIFY BELOW 
!
router bgp 100
no bgp network import-check
neighbor 2.2.2.20 remote-as 200
neighbor 2.2.2.20 description Router 2 of AS200
neighbor 8.8.8.40 remote-as 400
neighbor 8.8.8.40 description Router 4 of AS400

network 1.1.1.0/24
network 2.2.2.0/24
network 8.8.8.0/24

neighbor 2.2.2.20 prefix-list routerInr2 in
neighbor 2.2.2.20 prefix-list routerOutr2 out
neighbor 8.8.8.40 prefix-list routerInr4 in
neighbor 8.8.8.40 prefix-list routerOutr4 out

ip prefix-list routerInr2 permit 3.3.3.0/24
ip prefix-list routerInr2 permit 4.4.4.0/24
ip prefix-list routerInr2 permit 5.5.5.0/24
ip prefix-list routerInr2 permit 6.6.6.0/24
ip prefix-list routerInr2 permit 7.7.7.0/24

ip prefix-list routerOutr2 permit 1.1.1.0/24
ip prefix-list routerOutr2 permit 3.3.3.0/24
ip prefix-list routerOutr2 permit 4.4.4.0/24
ip prefix-list routerOutr2 permit 5.5.5.0/24
ip prefix-list routerOutr2 permit 6.6.6.0/24
ip prefix-list routerOutr2 permit 7.7.7.0/24
ip prefix-list routerOutr2 permit 8.8.8.0/24

ip prefix-list routerInr4 permit 3.3.3.0/24
ip prefix-list routerInr4 permit 4.4.4.0/24
ip prefix-list routerInr4 permit 5.5.5.0/24
ip prefix-list routerInr4 permit 6.6.6.0/24
ip prefix-list routerInr4 permit 7.7.7.0/24

ip prefix-list routerOutr4 permit 1.1.1.0/24
ip prefix-list routerOutr4 permit 2.2.2.0/24
ip prefix-list routerOutr4 permit 3.3.3.0/24
ip prefix-list routerOutr4 permit 4.4.4.0/24
ip prefix-list routerOutr4 permit 5.5.5.0/24
ip prefix-list routerOutr4 permit 6.6.6.0/24
ip prefix-list routerOutr4 permit 7.7.7.0/24


