!
! FRRouting configuration file
!
password zebra
enable password zebra
!
log file /var/log/frr/frr.log
!
!  BGP CONFIGURATION
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 65002
no bgp network import-check

network 198.51.100.4/30

neighbor 198.51.100.5 remote-as 65003
neighbor 198.51.100.5 description Router r3 of 65003

neighbor 203.0.113.5 remote-as 65004
neighbor 203.0.113.5 description Router inet of 65004
neighbor 203.0.113.5 default-originate


neighbor 198.51.100.5 prefix-list routerInr3 in
neighbor 198.51.100.5 prefix-list routerOutr3 out
neighbor 203.0.113.5 prefix-list routerIninet in
neighbor 203.0.113.5 prefix-list routerOutinet out

ip prefix-list routerInr3 permit 10.1.1.0/24
ip prefix-list routerInr3 permit 172.16.1.0/24

ip prefix-list routerOutr3 deny 10.1.1.0/24
ip prefix-list routerOutr3 deny 172.16.1.0/24
ip prefix-list routerOutr3 permit 0.0.0.0/0

ip prefix-list routerIninet deny 10.1.1.0/24
ip prefix-list routerIninet deny 172.16.1.0/24
ip prefix-list routerIninet deny 198.51.100.4/30
ip prefix-list routerIninet permit 0.0.0.0/0

ip prefix-list routerOutinet permit 10.1.1.0/24
ip prefix-list routerOutinet permit 172.16.1.0/24
ip prefix-list routerOutinet permit 198.51.100.4/30
