!
! FRRouting configuration file
!
password zebra
enable password zebra
!
log file /var/log/frr/frr.log
!
!  BGP CONFIGURATION
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 65004
no bgp network import-check
bgp bestpath compare-routerid

neighbor 203.0.113.1 remote-as 65001
neighbor 203.0.113.1 description Router isp1 of 65001

neighbor 203.0.113.6 remote-as 65002
neighbor 203.0.113.6 description Router isp2 of 65002

network 0.0.0.0/0

neighbor 203.0.113.1 prefix-list routerInisp1 in
neighbor 203.0.113.1 prefix-list routerOutisp1 out
neighbor 203.0.113.6 prefix-list routerInisp2 in
neighbor 203.0.113.6 prefix-list routerOutisp2 out

ip prefix-list routerInisp1 permit 10.1.1.0/24
ip prefix-list routerInisp1 permit 172.16.1.0/24
ip prefix-list routerInisp1 permit 198.51.100.0/30

ip prefix-list routerOutisp1 deny 10.1.1.0/24
ip prefix-list routerOutisp1 deny 172.16.1.0/24
ip prefix-list routerOutisp1 deny 198.51.100.0/30
ip prefix-list routerOutisp1 permit 0.0.0.0/0

ip prefix-list routerInisp2 permit 10.1.1.0/24
ip prefix-list routerInisp2 permit 172.16.1.0/24
ip prefix-list routerInisp2 permit 198.51.100.4/30

ip prefix-list routerOutisp2 deny 10.1.1.0/24
ip prefix-list routerOutisp2 deny 172.16.1.0/24
ip prefix-list routerOutisp2 deny 198.51.100.4/30
ip prefix-list routerOutisp2 permit 0.0.0.0/0

