LAB_DESCRIPTION="A multi-homed stub network"

r1[0]="A"
r1[image]="kathara/frr"

r2[0]="A"
r2[1]="B"
r2[image]="kathara/frr"

r3[0]="B"
r3[1]="C"
r3[2]="D"
r3[image]="kathara/frr"

isp1[0]="C"
isp1[1]="E"
isp1[image]="kathara/frr"

isp2[0]="D"
isp2[1]="F"
isp2[image]="kathara/frr"

inet[0]="E"
inet[1]="F"
inet[2]="G"
inet[image]="kathara/frr"
